# Project: Project2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"lib" -L"mingw32/lib" -mwindows -lgcc_eh -lallegro-5.0.10-monolith-mt -lallegro_image-5.0.10-mt -lallegro_primitives-5.0.10-mt -lallegro_font-5.0.10-mt -lallegro_ttf-5.0.10-mt   
INCS =  -I"include" 
CXXINCS =  -I"include" 
BIN  = Project2.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project2.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project2.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
